### ISSUE TITLE
References to secure coding practices quick reference guide

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-cornucopia#8]
The existing SCP references in Cornucopia refer to a [PDF version 2.0](https://owasp.org/www-pdf-archive/OWASP_SCP_Quick_Reference_Guide_v2.pdf) of the [Secure Coding Practices](https://github.com/OWASP/www-project-secure-coding-practices-quick-reference-guide) project. 

The SCP project is now archived, with checklists and content migrated to the Developer Guide
using issue [number #76](https://github.com/OWASP/www-project-developer-guide/issues/76)
and pull request [number #77](https://github.com/OWASP/www-project-developer-guide/pull/77).

Could we migrate the references to SCP in Cornucopia to references in Developer Guide?
I am not sure how to follow the existing SCP references to the version 2.0 of the SCP, is there an explanation somewhere?

**Comment by cw-owasp** [comment]
Hello Jon. Thank you for your interest. The SCP items were sequentially numbered and used as the basis of the original Cornucopia Ecommerce Website Edition card descriptions. I attach here a PDF of a .DOC created in 2014 which is annotated with the numbers.

But you are correct, SCP is not maintained and is now archived, so yes it will be better to map these to current OWASP projects, which we are hoping to do in a v1.3 in the nearish future.

[OWASP_SCP_Quick_Reference_Guide_v21.pdf](https://github.com/OWASP/www-project-cornucopia/files/12847365/OWASP_SCP_Quick_Reference_Guide_v21.pdf)

**Comment by jgadsden** [comment]
sounds good - the SCP references can be translated to Developer Guide references if you like?

**Comment by cw-owasp** [comment]
We are hoping to use Open CRE https://opencre.org (see also OWASP Integration Standards project https://owasp.org/www-project-integration-standards/ ), so any OWASP project can be mapped to each other. We hope to use CRE and match to many projects in the Cornucopia cards, and remove the legacy mappings.

**Comment by jgadsden** [comment]
OK, thanks @cw-owasp , I guess there will be an issue raised for that and I can close this one
