### ISSUE TITLE
Cornucopia Cards available via webshop

### ISSUE THREAD

**Issue by jefmeijvis** [OWASP/www-project-cornucopia#9]
Hi all,

On the OWASP project page there is a tab called "Get the cards".
It lists Agile Stationary as way of obtaining a Cornucopia set via a webshop, as opposed to playing it online or printing it yourself.
However, the Agile Stationary webshop seems to be out of stock for quite some time. 

We have printed a physical version that we put on sale over at our webshop at https://webshop.dotnetlab.eu/product/cornucopia-card-deck/. 
Could it be relevant to also list this webshop as a means of purchasing the cards?
This would mean people could choose between multiple 'vendors'. 
We could also provide discounts for OWASP members if there is any interest.

**Comment by cw-owasp** [comment]
Jef

Thanks very much for your interest in Cornucopia and letting us know about
dotNET lab's printed decks. They look great.

I have updated that tab on the Cornucopia website (source
https://github.com/OWASP/www-project-cornucopia/blob/master/tab_cards.md)
with details of your printed decks, so hopefully that will be live soon at
https://owasp.org/www-project-cornucopia/

Best regards

Colin Watson

**Comment by rewtd** [comment]
Now that was an awesome Valentine's Day gift! Closing as the update is live.
